package com.diagnostic.mammogram.util;

import com.diagnostic.mammogram.model.Report;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;

@Component
public class PdfReportGenerator {

    public byte[] generatePdf(Report report) throws DocumentException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        Document document = new Document();
        PdfWriter.getInstance(document, outputStream);

        document.open();

        // Add title
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
        Paragraph title = new Paragraph("Mammogram Analysis Report", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        // Add patient information
        document.add(new Paragraph("\n"));
        document.add(new Paragraph("Patient Information:", FontFactory.getFont(FontFactory.HELVETICA_BOLD)));
        document.add(new Paragraph("Name: " + report.getMammogram().getPatient().getFullName()));
        document.add(new Paragraph("Age: " + report.getMammogram().getPatient().getAge()));
        document.add(new Paragraph("Gender: " + report.getMammogram().getPatient().getGender()));

        // Add mammogram details
        document.add(new Paragraph("\n"));
        document.add(new Paragraph("Mammogram Details:", FontFactory.getFont(FontFactory.HELVETICA_BOLD)));
        document.add(new Paragraph("Date Taken: " + report.getMammogram().getUploadDate()));
        document.add(new Paragraph("Notes: " + report.getMammogram().getNotes()));

        // Add findings
        document.add(new Paragraph("\n"));
        document.add(new Paragraph("Findings:", FontFactory.getFont(FontFactory.HELVETICA_BOLD)));
        document.add(new Paragraph(report.getFindings()));

        // Add recommendations
        document.add(new Paragraph("\n"));
        document.add(new Paragraph("Recommendations:", FontFactory.getFont(FontFactory.HELVETICA_BOLD)));
        document.add(new Paragraph(report.getRecommendations()));

        // Add footer
        document.add(new Paragraph("\n\n"));
        document.add(new Paragraph("Generated by: " + report.getCreatedBy()));
        document.add(new Paragraph("Date: " + report.getCreatedAt()));

        document.close();
        return outputStream.toByteArray();
    }
}