package com.diagnostic.mammogram.dto.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import jakarta.validation.constraints.Size; // For string length validation

/**
 * DTO for updating an existing AI diagnosis result.
 * Fields are optional as only specific parts might be updated.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AIDiagnosisUpdateRequest {

    // Prediction might be updated if there's a manual override, though less common.
    @Size(max = 255, message = "Prediction cannot exceed 255 characters.")
    private String prediction;

    // Detailed findings are likely to be updated/added by a human expert.
    @Size(max = 1000, message = "Detailed findings cannot exceed 1000 characters.")
    private String detailedFindings;

    // Recommendation is also likely to be updated/added by a human expert.
    @Size(max = 1000, message = "Recommendation cannot exceed 1000 characters.")
    private String recommendation;

    // Note: confidenceScore and probabilities are typically generated by the AI
    // and would not be updated manually via this DTO. If a re-analysis is needed,
    // that would be a separate process.
}
